FROM ruby:3.4.5-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git curl libpq-dev libyaml-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock .ruby-version ./
RUN bundle install

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
