slug: vos-interlocuteurs-selon-le-type-d-api
h1: Vos interlocuteurs selon le type d'API
title: Vos interlocuteurs selon le type d'API
description: >-
  Identifiez votre interlocuteur selon le type d'API que vous intégrez et
  selon votre situation.
keywords: [API, Guide métier, DSI, MOA, Éditeur de logiciels]
hero_backdrop_gradient: "linear-gradient(135deg, #decdbd 0%, #e3e3fd 100%)"
sections:
  types-api: Types d'API
  interlocuteurs: Acteurs et interlocuteurs
  recapitulatif: Pour résumer
